const text = {
  chapter1: { title: 'CHAPTER 1', content: `There were two tasks I had on my mind upon waking to another sunless sky; the first was to prove my sanity, and the second was to secure state funding for an interstellar voyage.\n

  I woke in fright, with a hangover so intense it was practically spiritual. The campus, on which I worked and lived as temporary workshop facilitator, was a sterile network of interconnected lawns and poured concrete buildings, which would be crowded with the families of graduates. The day would not be an easy one. I felt around for a bag of water, and managed to locate it without lifting my spinning head from the pillow. Today will be difficult. I repeated this to myself, hoping the acknowledgement would absolve me of the previous night’s discretions.\n

  As a temporary workshop facilitator, I was not paid, but did receive one free meal in the cafeteria daily, as well as heavily subsidized campus housing. My apartment in SB-28, or sub basement floor 28, contained one folding table, two folding chairs (although I had no partner), a closet, and an inflatable mattress that, when deflated, could be easily stored in the closet. There were two communal bathrooms at each end of the hall, cluttered with 40 odd peoples toiletry necessities.\n

  I enjoy some form of clutter. There’s something to be said for a desk covered in dusty papers with mismatched stationary. I’ve never found character in a hospital. Unfortunately, the lack of actual space anywhere on campus made clutter a hard fact. So, in my quarters, I built a series of shelves along the walls, from floor to ceiling, no more than one and a half feet in width. Each additional vertical/horizontal square foot acting as an expression of my truest self.\n

  My workshop, Memories of Unlearned Behavior, carried no credits, and was, as a result of this, poorly attended. ‘There are threats of asteroids, ice caps turned to floodwaters,’ the school paper had written not long after my workshop began, ‘ and sentient A.I. turning vindictive….We’re supposed to be interested in how experiments...that involve flatworms eating other flatworms, have resulted in the canibal worms gaining sensory knowledge from the cannibalized worms?’\n

  This was, obviously, a gross simplification of my first paper on the subject ‘Vitamin D Testing of the Flatworm: Electric Shock and Unlearned Behavior.’ By the start of my workshop I’d written five others, and had advanced beyond flatworms, to sea snails, mice, rats, primates, and unknown to most, humans.\n

  The lab was only slightly larger than my apartment, and three days a week doubled as classroom for the workshop. This day would be one of those days, so I covered some of the tanks and locked away any notes that might contradict my first task, therefore greatly jeopardizing the second.` },

  chapter2: { title: 'CHAPTER 2', content: `Originally, I’d majored in biological research science. Not long before graduation I was drafted into a satellite repair and defense unit. I’d be a RAD. This was the war effort at work. Somewhere purpose was being manufactured. As a research scientist the change took effort, but the physical demands were somewhat welcome. The laboratory days of youth were replaced with calisthenics, and songs of discipline. I had nothing concrete towards which to rebel. Everything terrible had already been decided, and begun. So I conformed to my new responsibilities.\n

  Training required a level of awareness that was foreign to my wandering mind. Dreadful thoughts, and happy ones that sat at the forefront of everything were replaced by the basics: left hand forward, right hand check belt, neck still, eyes up, legs in position, heart rate stable, and so on.\n

  If you are careless, death. If you hesitate, death. Position yourself, at all times, so that you are facing whatever is coming your direction. This may seem counter intuitive, but turning your back to debris only increases the chances that something the size of an arrowhead hits your rear at the right angle and shuts down your suit’s central computer, or worse, breaches your exterior reserve of oxygen. Then death. The boot camp instructor/soon to be captain was neither menacing nor loving, only honest.\n

  I don’t recall them ever providing us with a word of encouragement or insult, just facts and statistics. This many died last month, now here’s every reason why, and how this could of been prevented. We sat in a series of dark classrooms, watching the raw video feed from the suits of the fallen. Meticulously analyzing every incorrect movement that lead them from duty to death. I remember one where two units of debris, each the size of my twin mattress, collided, probably only 50 meters from the RAD. Rather then analyzing the likely trajectory, or turning their back to make an ill planned, and unlikely to work, escape - they remained in their position.` },


  // EVERYTHING BELOW IS COPIES FOR TESTING


  chapter3: { title: 'CHAPTER 3', content: `Originally, I’d majored in biological research science. Not long before graduation I was drafted into a satellite repair and defense unit. I’d be a RAD. This was the war effort at work. Somewhere purpose was being manufactured. As a research scientist the change took effort, but the physical demands were somewhat welcome. The laboratory days of youth were replaced with calisthenics, and songs of discipline. I had nothing concrete towards which to rebel. Everything terrible had already been decided, and begun. So I conformed to my new responsibilities.\n

  Training required a level of awareness that was foreign to my wandering mind. Dreadful thoughts, and happy ones that sat at the forefront of everything were replaced by the basics: left hand forward, right hand check belt, neck still, eyes up, legs in position, heart rate stable, and so on.\n

  If you are careless, death. If you hesitate, death. Position yourself, at all times, so that you are facing whatever is coming your direction. This may seem counter intuitive, but turning your back to debris only increases the chances that something the size of an arrowhead hits your rear at the right angle and shuts down your suit’s central computer, or worse, breaches your exterior reserve of oxygen. Then death. The boot camp instructor/soon to be captain was neither menacing nor loving, only honest.\n

  I don’t recall them ever providing us with a word of encouragement or insult, just facts and statistics. This many died last month, now here’s every reason why, and how this could of been prevented. We sat in a series of dark classrooms, watching the raw video feed from the suits of the fallen. Meticulously analyzing every incorrect movement that lead them from duty to death. I remember one where two units of debris, each the size of my twin mattress, collided, probably only 50 meters from the RAD. Rather then analyzing the likely trajectory, or turning their back to make an ill planned, and unlikely to work, escape - they remained in their position.` },
  chapter4: { title: 'CHAPTER 4', content: `Originally, I’d majored in biological research science. Not long before graduation I was drafted into a satellite repair and defense unit. I’d be a RAD. This was the war effort at work. Somewhere purpose was being manufactured. As a research scientist the change took effort, but the physical demands were somewhat welcome. The laboratory days of youth were replaced with calisthenics, and songs of discipline. I had nothing concrete towards which to rebel. Everything terrible had already been decided, and begun. So I conformed to my new responsibilities.\n

  Training required a level of awareness that was foreign to my wandering mind. Dreadful thoughts, and happy ones that sat at the forefront of everything were replaced by the basics: left hand forward, right hand check belt, neck still, eyes up, legs in position, heart rate stable, and so on.\n

  If you are careless, death. If you hesitate, death. Position yourself, at all times, so that you are facing whatever is coming your direction. This may seem counter intuitive, but turning your back to debris only increases the chances that something the size of an arrowhead hits your rear at the right angle and shuts down your suit’s central computer, or worse, breaches your exterior reserve of oxygen. Then death. The boot camp instructor/soon to be captain was neither menacing nor loving, only honest.\n

  I don’t recall them ever providing us with a word of encouragement or insult, just facts and statistics. This many died last month, now here’s every reason why, and how this could of been prevented. We sat in a series of dark classrooms, watching the raw video feed from the suits of the fallen. Meticulously analyzing every incorrect movement that lead them from duty to death. I remember one where two units of debris, each the size of my twin mattress, collided, probably only 50 meters from the RAD. Rather then analyzing the likely trajectory, or turning their back to make an ill planned, and unlikely to work, escape - they remained in their position.` },
  chapter5: { title: 'CHAPTER 5', content: `Originally, I’d majored in biological research science. Not long before graduation I was drafted into a satellite repair and defense unit. I’d be a RAD. This was the war effort at work. Somewhere purpose was being manufactured. As a research scientist the change took effort, but the physical demands were somewhat welcome. The laboratory days of youth were replaced with calisthenics, and songs of discipline. I had nothing concrete towards which to rebel. Everything terrible had already been decided, and begun. So I conformed to my new responsibilities.\n

  Training required a level of awareness that was foreign to my wandering mind. Dreadful thoughts, and happy ones that sat at the forefront of everything were replaced by the basics: left hand forward, right hand check belt, neck still, eyes up, legs in position, heart rate stable, and so on.\n

  If you are careless, death. If you hesitate, death. Position yourself, at all times, so that you are facing whatever is coming your direction. This may seem counter intuitive, but turning your back to debris only increases the chances that something the size of an arrowhead hits your rear at the right angle and shuts down your suit’s central computer, or worse, breaches your exterior reserve of oxygen. Then death. The boot camp instructor/soon to be captain was neither menacing nor loving, only honest.\n

  I don’t recall them ever providing us with a word of encouragement or insult, just facts and statistics. This many died last month, now here’s every reason why, and how this could of been prevented. We sat in a series of dark classrooms, watching the raw video feed from the suits of the fallen. Meticulously analyzing every incorrect movement that lead them from duty to death. I remember one where two units of debris, each the size of my twin mattress, collided, probably only 50 meters from the RAD. Rather then analyzing the likely trajectory, or turning their back to make an ill planned, and unlikely to work, escape - they remained in their position.` },
  chapter6: { title: 'CHAPTER 5', content: `Originally, I’d majored in biological research science. Not long before graduation I was drafted into a satellite repair and defense unit. I’d be a RAD. This was the war effort at work. Somewhere purpose was being manufactured. As a research scientist the change took effort, but the physical demands were somewhat welcome. The laboratory days of youth were replaced with calisthenics, and songs of discipline. I had nothing concrete towards which to rebel. Everything terrible had already been decided, and begun. So I conformed to my new responsibilities.\n

  Training required a level of awareness that was foreign to my wandering mind. Dreadful thoughts, and happy ones that sat at the forefront of everything were replaced by the basics: left hand forward, right hand check belt, neck still, eyes up, legs in position, heart rate stable, and so on.\n

  If you are careless, death. If you hesitate, death. Position yourself, at all times, so that you are facing whatever is coming your direction. This may seem counter intuitive, but turning your back to debris only increases the chances that something the size of an arrowhead hits your rear at the right angle and shuts down your suit’s central computer, or worse, breaches your exterior reserve of oxygen. Then death. The boot camp instructor/soon to be captain was neither menacing nor loving, only honest.\n

  I don’t recall them ever providing us with a word of encouragement or insult, just facts and statistics. This many died last month, now here’s every reason why, and how this could of been prevented. We sat in a series of dark classrooms, watching the raw video feed from the suits of the fallen. Meticulously analyzing every incorrect movement that lead them from duty to death. I remember one where two units of debris, each the size of my twin mattress, collided, probably only 50 meters from the RAD. Rather then analyzing the likely trajectory, or turning their back to make an ill planned, and unlikely to work, escape - they remained in their position.` },
}

export default text;
